# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuPreferences = QtWidgets.QMenu(self.menubar)
        self.menuPreferences.setObjectName("menuPreferences")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(Main)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("icons/close_111152.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen = QtWidgets.QAction(Main)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap("icons/openfolderwithfile_122800.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(Main)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap("icons/savetheapplication_guardar_2958.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(Main)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap("icons/save_3621.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.actionSave_as.setIcon(icon3)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionClose_Image = QtWidgets.QAction(Main)
        self.actionClose_Image.setIcon(icon)
        self.actionClose_Image.setObjectName("actionClose_Image")
        self.actionReset_Image = QtWidgets.QAction(Main)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap("icons/reset_undo_arrow_icon_149006.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionReset_Image.setIcon(icon4)
        self.actionReset_Image.setObjectName("actionReset_Image")
        self.actionSave_copy = QtWidgets.QAction(Main)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap("icons/copy_icon-icons.com_64492.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionSave_copy.setIcon(icon5)
        self.actionSave_copy.setObjectName("actionSave_copy")
        self.actionLanguage = QtWidgets.QAction(Main)
        self.actionLanguage.setObjectName("actionLanguage")
        self.actionEditor = QtWidgets.QAction(Main)
        self.actionEditor.setObjectName("actionEditor")
        self.actionOn = QtWidgets.QAction(Main)
        self.actionOn.setObjectName("actionOn")
        self.actionContributer = QtWidgets.QAction(Main)
        self.actionContributer.setObjectName("actionContributer")
        self.actionHelp = QtWidgets.QAction(Main)
        self.actionHelp.setObjectName("actionHelp")
        self.actionDocumentation = QtWidgets.QAction(Main)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionPrint = QtWidgets.QAction(Main)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(
            QtGui.QPixmap("icons/Print_icon-icons.com_55835.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionPrint.setIcon(icon6)
        self.actionPrint.setObjectName("actionPrint")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionSave_copy)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionReset_Image)
        self.menuFile.addAction(self.actionClose_Image)
        self.menuFile.addAction(self.actionExit)
        self.menuPreferences.addAction(self.actionLanguage)
        self.menuPreferences.addAction(self.actionEditor)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionOn)
        self.menuHelp.addAction(self.actionContributer)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPreferences.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Main"))
        self.menuFile.setTitle(_translate("Main", "File"))
        self.menuPreferences.setTitle(_translate("Main", "Preferences"))
        self.menuHelp.setTitle(_translate("Main", "Help"))
        self.actionExit.setText(_translate("Main", "Exit"))
        self.actionExit.setShortcut(_translate("Main", "Ctrl+Q"))
        self.actionOpen.setText(_translate("Main", "Open"))
        self.actionOpen.setShortcut(_translate("Main", "Ctrl+O"))
        self.actionSave.setText(_translate("Main", "Save"))
        self.actionSave.setShortcut(_translate("Main", "Ctrl+S"))
        self.actionSave_as.setText(_translate("Main", "Save as"))
        self.actionSave_as.setShortcut(_translate("Main", "Ctrl+Shift+S"))
        self.actionClose_Image.setText(_translate("Main", "Close Image"))
        self.actionClose_Image.setShortcut(_translate("Main", "Ctrl+W"))
        self.actionReset_Image.setText(_translate("Main", "Reset Image"))
        self.actionSave_copy.setText(_translate("Main", "Save copy"))
        self.actionLanguage.setText(_translate("Main", "Language"))
        self.actionEditor.setText(_translate("Main", "Editor"))
        self.actionOn.setText(_translate("Main", "On"))
        self.actionContributer.setText(_translate("Main", "Contribute"))
        self.actionHelp.setText(_translate("Main", "Help"))
        self.actionHelp.setShortcut(_translate("Main", "F1"))
        self.actionDocumentation.setText(_translate("Main", "Documentation"))
        self.actionPrint.setText(_translate("Main", "Print"))
        self.actionPrint.setShortcut(_translate("Main", "Ctrl+P"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
